apiVersion: apps/v1
kind: Deployment
metadata:
  name: gke-deploy-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gke-deploy
  template:
    metadata:
      labels:
        app: gke-deploy
    spec:
      containers:
        - name: gke-deploy-deployment
          image: us-central1-docker.pkg.dev/secret-retrieval-deployment/deployment-cluster/gke-deploy:0.1.6
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /var/config
              name: confluent
      serviceAccountName: deployment-access-secret
      terminationGracePeriodSeconds: 30
      volumes:
        - name: confluent
          csi:
            driver: secrets-store-gke.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: confluent-secret