apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    iam.gke.io/gcp-service-account: deployment-account@secret-retrieval-deployment.iam.gserviceaccount.com
  name: kube-deployment-account
