name: Deploy to GKE

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
#      #### Build Java Jar
#      - name: Checkout sources
#        uses: actions/checkout@v4
#
#      - name: Setup Gradle
#        uses: actions/setup-java@v4
#        with:
#          distribution: temurin
#          java-version: 17
#
#      - name: Build with Gradle
#        run: ./gradlew build
#
#      #### Prep Docker Image
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
#
#      - name: Build and push
#        uses: docker/build-push-action@v3
#        with:
#          context: .
#          push: true
#          tags: tobecvs/gcp-private:v0.0.1

      #########    Access GCP    #########
      - name: Authenticate with GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.COMPUTE_ENGINE_CREDENTIALS }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: 'first-solo-java-deploy'
          install_components: gke-gcloud-auth-plugin

      - name: Validate GKE Extensions
        run: gcloud components list

#########    Deploy Image    #########
      - name: Deploy to GKE
        run: |
          gcloud container clusters get-credentials first-solo-java-deploy --region us-central1
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml

#      - name: Get GKE Credentials
#        uses: google-github-actions/get-gke-credentials@v2
#        with:
#          cluster_name: ${{ env.CLUSTER_NAME }}
#          location: ${{ env.ZONE }}
#
#      - name: Configure kubectl
#        run: |
#          gcloud config set project $PROJECT_ID
#          gcloud config set compute/zone $ZONE
#          gcloud container clusters get-credentials $CLUSTER_NAME
#          gcloud components install gke-gcloud-auth-plugin
#
#      - name: Validate Kubectl
#        run: |
#          kubectl version --client
#          gke-gcloud-auth-plugin --version
#
#      - name: Apply deployment
#        run: |
#          kubectl apply -f psa.yaml
#          kubectl apply -f gcp-confluent-secret.yaml
#          kubectl apply -f deployment.yaml
